name: PHP quality checks

on:
  pull_request:
    branches: [ main ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHPStan analyse of codebase
      run: composer run-script phpstan-check
      if: ${{ always() }}
    
    - name: Psalm analyse of codebase
      run: composer run-script psalm-check
      if: ${{ always() }}
    
    - name: PHP Magic Number Detector analyse of codebase
      run: composer run-script phpmnd-check
      if: ${{ always() }}


    


